# Generated by Django 3.0.2 on 2020-04-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_clientdetails_cityuser'),
        ('travello', '0004_auto_20200204_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='destination_name',
            field=models.ManyToManyField(to='accounts.clientdetails'),
        ),
    ]
