# Generated by Django 3.0.2 on 2020-04-05 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0005_destination_destination_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='destination_name',
        ),
    ]
