# Generated by Django 3.0.2 on 2020-04-05 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0007_destination_destinationuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='destinationuser',
        ),
    ]
