# Generated by Django 3.0.2 on 2020-04-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0008_remove_destination_destinationuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='agentnumber',
            field=models.CharField(default='8237377298', max_length=10),
        ),
    ]
