# Generated by Django 3.0.2 on 2020-05-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0009_destination_agentnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='agent_address',
            field=models.CharField(default='not define', max_length=50),
        ),
    ]
