# Generated by Django 3.0.2 on 2020-05-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0010_destination_agent_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(default='vdx', max_length=50),
        ),
    ]
