# Generated by Django 3.0.2 on 2020-03-23 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_clientdetails_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdetails',
            name='term',
        ),
    ]
