# Generated by Django 3.0.2 on 2020-03-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_delete_clientdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('people', models.IntegerField()),
                ('street', models.CharField(max_length=50)),
                ('additionalinformation', models.CharField(max_length=50)),
                ('zip', models.IntegerField()),
                ('place', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('code', models.IntegerField()),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
