# Generated by Django 3.0.2 on 2020-03-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200323_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='additionalinformation',
            field=models.CharField(default='vdx', max_length=50),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='code',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='country',
            field=models.CharField(default='vdx', max_length=50),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='last_name',
            field=models.CharField(default='vdx', max_length=50),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='middle_name',
            field=models.CharField(default='vdx', max_length=50),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='occupation',
            field=models.CharField(default='vdx', max_length=50),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='people',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='phone',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='place',
            field=models.CharField(default='vdx', max_length=50),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='status',
            field=models.CharField(default='vdx', max_length=50),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='street',
            field=models.CharField(default='vdx', max_length=50),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='zip1',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='clientdetails',
            name='first_name',
            field=models.CharField(default='vdx', max_length=50),
        ),
    ]
