# Generated by Django 3.0.2 on 2020-03-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200324_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='additionalinformation',
            field=models.CharField(default='vdx', max_length=50),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='people',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='street',
            field=models.CharField(default='vdx', max_length=50),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='zip1',
            field=models.IntegerField(default=1),
        ),
    ]
