# Generated by Django 3.0.2 on 2020-03-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200324_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='place',
            field=models.CharField(default='vdx', max_length=50),
        ),
    ]
