# Generated by Django 3.0.2 on 2020-03-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_clientdetails_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='code',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='country',
            field=models.CharField(default='vdx', max_length=50),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='phone',
            field=models.IntegerField(default=1),
        ),
    ]
