# Generated by Django 3.0.2 on 2020-03-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200324_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='term',
            field=models.BooleanField(default='True'),
        ),
        migrations.AlterField(
            model_name='clientdetails',
            name='phone',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
