# Generated by Django 3.0.2 on 2020-03-28 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_clientdetails_term'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdetails',
            name='gmail',
        ),
        migrations.RemoveField(
            model_name='clientdetails',
            name='phone',
        ),
    ]
