# Generated by Django 3.0.2 on 2020-03-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20200328_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='gmail',
            field=models.CharField(default='vdx', max_length=50),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='phone',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
