# Generated by Django 3.0.2 on 2020-03-28 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20200328_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdetails',
            name='gmail',
        ),
    ]
