# Generated by Django 3.0.2 on 2020-03-28 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0020_remove_clientdetails_gmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='gmail',
            field=models.EmailField(default='gsh', max_length=254),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
