# Generated by Django 3.0.2 on 2020-03-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20200328_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='gmail',
            field=models.CharField(default='gsh', max_length=50),
        ),
    ]
