# Generated by Django 3.0.2 on 2020-03-28 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20200329_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdetails',
            name='gmail',
        ),
    ]
