# Generated by Django 3.0.2 on 2020-03-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_remove_clientdetails_gmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='gmail',
            field=models.CharField(default='gsh', max_length=50),
        ),
    ]
