# Generated by Django 3.0.2 on 2020-04-01 20:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_clientdetails_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
