# Generated by Django 3.0.2 on 2020-04-01 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_clientdetails_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdetails',
            name='city',
        ),
    ]
