# Generated by Django 3.0.2 on 2020-04-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_remove_clientdetails_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='datetime',
            field=models.CharField(max_length=50),
        ),
    ]
