# Generated by Django 3.0.2 on 2020-04-02 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20200402_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='datetime',
            field=models.CharField(default=datetime.datetime.now, max_length=50),
        ),
    ]
