# Generated by Django 3.0.2 on 2020-04-02 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20200402_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientdetails',
            old_name='datetime',
            new_name='Date_From',
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='Date_To',
            field=models.CharField(default=datetime.datetime.now, max_length=50),
        ),
    ]
