# Generated by Django 3.0.2 on 2020-04-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0006_remove_destination_destination_name'),
        ('accounts', '0031_clientdetails_cityuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='destinationuser',
            field=models.ManyToManyField(to='travello.Destination'),
        ),
    ]
