# Generated by Django 3.0.2 on 2020-04-05 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_clientdetails_destinationuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdetails',
            name='destinationuser',
        ),
    ]
