# Generated by Django 3.0.2 on 2020-04-05 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_clientdetails_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdetails',
            name='Destination',
        ),
    ]
