# Generated by Django 3.0.2 on 2020-04-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0008_remove_destination_destinationuser'),
        ('accounts', '0035_remove_clientdetails_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='Destination',
            field=models.ManyToManyField(to='travello.Destination'),
        ),
    ]
