# Generated by Django 3.0.2 on 2020-04-05 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_auto_20200406_0302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientdetails',
            old_name='name',
            new_name='cityuser',
        ),
    ]
