# Generated by Django 3.0.2 on 2020-04-06 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_auto_20200406_0311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientdetails',
            old_name='cityuser',
            new_name='city_name',
        ),
        migrations.RemoveField(
            model_name='clientdetails',
            name='Destination',
        ),
    ]
