# Generated by Django 3.0.2 on 2020-04-07 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0008_remove_destination_destinationuser'),
        ('accounts', '0040_yourtrips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yourtrips',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travello.Destination'),
        ),
        migrations.AlterField(
            model_name='yourtrips',
            name='trips',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.clientdetails'),
        ),
    ]
