# Generated by Django 3.0.2 on 2020-04-07 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_auto_20200407_1435'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Yourtrips',
        ),
    ]
