# Generated by Django 3.0.2 on 2020-04-07 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0008_remove_destination_destinationuser'),
        ('accounts', '0044_auto_20200407_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='travello.Destination'),
        ),
        migrations.DeleteModel(
            name='Yourtrips',
        ),
    ]
