# Generated by Django 3.0.2 on 2020-05-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_auto_20200506_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdetails',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='clientdetails',
            name='people',
        ),
        migrations.RemoveField(
            model_name='clientdetails',
            name='place',
        ),
        migrations.RemoveField(
            model_name='clientdetails',
            name='source',
        ),
        migrations.RemoveField(
            model_name='clientdetails',
            name='street',
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='address_line1',
            field=models.CharField(default='vdx', max_length=50),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='address_line2',
            field=models.CharField(default='vdx', max_length=50),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='city',
            field=models.CharField(default='vdx', max_length=50),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='people_childern',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='people_female',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='people_mens',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='state',
            field=models.CharField(default='vdx', max_length=50),
        ),
    ]
