# Generated by Django 3.0.2 on 2020-05-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_auto_20200509_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='any_message',
            field=models.CharField(default='vdx', max_length=50),
        ),
    ]
