# Generated by Django 3.0.2 on 2020-05-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_auto_20200510_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='gmail',
            field=models.EmailField(default='gsh', max_length=50),
        ),
    ]
