# Generated by Django 3.0.6 on 2020-05-15 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0011_auto_20200511_1803'),
        ('accounts', '0052_auto_20200513_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='city_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travello.Destination'),
        ),
    ]
