# Generated by Django 3.0.6 on 2020-05-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_auto_20200515_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='city_name',
            field=models.CharField(default='vdx', max_length=50),
        ),
    ]
